package rules;
import com.ruoyi.drools.domain.Points
rule "drools1"
    when
        $p:Points(eventType1 == 1)
    then
        double originalIntegrall = $p.getOriginalIntegral1()+5;
        $p.setServiceScore(originalIntegrall);
        update($p)
        System.out.println("触发无有责取消=================司机服务分+"+$p.getServiceScore());
end
rule "drools2"
    when
        $p:Points(eventType1 == 2)
    then
        double originalIntegrall = $p.getOriginalIntegral1()+7;
        $p.setTripScore(originalIntegrall);
        update($p)
        System.out.println("触发无神访不合格订单=================出行分+"+$p.getTripScore());
end

rule "drools3"
    when
        $p:Points(eventType1 == 3)
    then
        double originalIntegrall = $p.getOriginalIntegral1()+2.5;
        $p.setServiceScore(originalIntegrall);
        update($p)
        System.out.println("触发行程结束无好评=================服务分+"+$p.getServiceScore());
end


rule "drools4"
    when
        $p:Points(eventType1 == 4)
    then
        double originalIntegrall = $p.getOriginalIntegral1()+3;
        $p.setServiceScore(originalIntegrall);
        update($p)
        System.out.println("触发行程结束有好评=================服务分+"+$p.getServiceScore());
end


rule "drools5"
    when
        $p:Points(eventType1 == 5)
    then
        double originalIntegrall = $p.getOriginalIntegral1()+1;
        $p.setServiceScore(originalIntegrall);
        update($p)
        System.out.println("触发触发乘客赠送小红花=================服务分+"+$p.getServiceScore());
end


rule "drools6"
    when
        $p:Points(eventType1 == 6)
    then
        double originalIntegrall = $p.getOriginalIntegral1()+3;
        $p.setComplianceScore(originalIntegrall);
        update($p)
        System.out.println("触发完成课程学习---------------合规分+"+$p.getComplianceScore());
end
rule "drools7"
    when
        $p:Points(eventType == 1)
    then
        double originalIntegrall = $p.getOriginalIntegral()-15;
        $p.setServiceScore(originalIntegrall);
        update($p)
        System.out.println("触发乘客投诉---------------服务分"+$p.getServiceScore());
end
rule "drools8"
    when
        $p:Points(eventType == 2)
    then
        double originalIntegrall = $p.getOriginalIntegral()-5;
        $p.setTripScore(originalIntegrall);
        update($p)
        System.out.println("触发因司机责任乘客取消订单---------------出行分"+$p.getTripScore());
end
rule "drools9"
    when
        $p:Points(eventType == 3)
    then
        double originalIntegrall = $p.getOriginalIntegral()-7;
        $p.setComplianceScore(originalIntegrall);
        update($p)
        System.out.println("触发司机接受访问不合格---------------合规分"+$p.getComplianceScore());
end